---
title: "Weather Preferences in the United States"
subtitle: "Summary Report for the `r params$region`Region"
author: "Monica Cortinas"
date: "`r format(Sys.Date(), '%A, %B %d, %Y')`"
output: 
  slidy_presentation:
    logo: images/sunstar.png
params:
  region: 
    label: "Region:"
    value: Mountain
    input: select
    choices: ["East North Central","East South Central", "Middle Atlantic","Mountain", "New England", "Pacific","South Atlantic", "West North Central", "West South Central"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE }
knitr::read_chunk("code/setup.R")
```

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
```

```{r loadData}
```

```{r child="text/BackgroundSection.Rmd"}

```


```{r child="text/PurposeSection.Rmd"}

```


```{r makePlot, code=readLines("code/makeplot.R")}

```


Necesitamos los dos: uno para leer el código y otro para mostrar el gráfico:

```{r, echo=TRUE}
knitr::read_chunk("code/makeplot.R")
```

```{r makeCharts, echo=TRUE}

```
